[package]
name = "sg-http-rust"
version = "0.1.1"
authors = ["Samuel Clarke <sam.clarke@cumulusvfx.com>"]

[dependencies]
serde="1.0"
serde_derive="1.0"
serde_json="1.0"
url="1.7.1"
reqwest="0.9.2"
env_logger="0.5.13"